import type { Metadata } from "next";
import { Lato, Roboto } from "next/font/google";
import Footer from "./components/footer";
import "./globals.css";

const lato = Lato({
  weight: ["400", "700"],
  subsets: ["latin"],
})

const roboto = Roboto({
  weight: ["400", "500", "700"],
  subsets: ["latin"],
})

export const metadata: Metadata = {
  title: "A&N Fabrication Website",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${roboto.className} ${lato.className} antialiased`}
      >
        <main>
          {children}
        </main>
        <Footer/>
      </body>
    </html>
  );
}
